import { Inter, Roboto } from "next/font/google";
import "./globals.css";
import Navigation from "@/ui/navigation-bar/navigation";
import Footer from "@/ui/footer/footer";

const roboto = Roboto({ 
  weight: ['400', '700', '100', '300' ,'500', '900'],
  subsets: ["latin"]
 });

export const metadata = {
  title: "MesSQQ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${roboto.className}`}>
        
        <Navigation/>
        {children}
        <Footer/>
        
        </body>
    </html>
  );
}
