
import "./globals.css";
import { Montserrat } from 'next/font/google'
import Navigation from "@/ui/navigation-bar/navigation";
import Footer from "@/ui/footer/footer";
import Provider from "@/provider/provider";

export const metadata = {
  title: "MesSQQ",
  description: "Generated by create next app",
};

const montserrat = Montserrat(
  {
   subsets: ['latin'] ,
   weight:['100', '200', '300', '400', '500', '600', '700', '800']
  }
)


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${montserrat.className} dark:bg-[#222] dark:text-white`} suppressHydrationWarning>
        <Provider>

        <Navigation />
        {children}
        <Footer/>

        </Provider>
       
        </body>
    </html>
  );
}
